In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import urllib

server = 'RDsDevice\SQLEXPRESS01'
database = 'Inventory'

connection_string = (
    "DRIVER={ODBC Driver 17 for SQL Server};"
    f"SERVER={server};"
    f"DATABASE={database};"
    "Trusted_Connection=yes;"
)

params = urllib.parse.quote_plus(connection_string)

engine = create_engine(
    f"mssql+pyodbc:///?odbc_connect={params}"
)

In [2]:
query = "SELECT * FROM Vendor____Sales____Summary"

df = pd.read_sql(query, engine)

C:\Users\rd000\anaconda3\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

In [3]:
df

,VendorNo,Brand,Description,FreightCost,vendorname,purchaseprice,TotalPurchaseQuantity,TotalPurchaseDollar,volume,SellingPrice,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,2,90085,Ch Lilian 09 Ladouys St Este,27.080001,"IRA GOLDMAN AND WILLIAMS, LLP",23.860001,8,190.880005,750,36.990002,665.820019,295.920013,18.0,2.000000
1,2,90609,Flavor Essence Variety 5 Pak,27.080001,"IRA GOLDMAN AND WILLIAMS, LLP",17.000000,320,5440.000000,162.5,24.990000,599.759998,449.819996,24.0,0.520000
2,54,990,Ethyl Alcohol 200 Proof,0.480000,AAPER ALCOHOL & CHEMICAL CO,105.070000,1,105.070000,3750,134.490005,NaN,NaN,NaN,NaN
3,60,771,Bak's Krupnik Honey Liqueur,367.520002,ADAMBA IMPORTS INTL INC,11.440000,39,446.159996,750,14.990000,704.529989,494.669992,47.0,37.010001
4,60,3401,Vesica Vodka,367.520002,ADAMBA IMPORTS INTL INC,11.100000,6,66.599998,1750,14.990000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,173357,2804,Camp Robber Whiskey,202.500001,TAMWORTH DISTILLING,32.139999,210,6749.399887,750,44.990002,6298.600163,3194.290119,140.0,110.330001
10688,173357,3666,Art in the Age Chicory Root,202.500001,TAMWORTH DISTILLING,18.790001,520,9770.799988,375,24.990000,8996.399963,4873.049955,360.0,141.189998
10689,173357,3848,Chicory Root Vodka,202.500001,TAMWORTH DISTILLING,23.299999,28,652.400009,750,30.990000,185.939999,92.969999,6.0,4.710000
10690,173357,3909,White Mountain Vodka,202.500001,TAMWORTH DISTILLING,19.370001,1232,23863.840233,750,24.990000,24540.179880,14469.209867,982.0,773.870011
10691,201359,90609,Flavor Essence Variety 5 Pak,0.090000,FLAVOR ESSENCE INC,17.000000,1,17.000000,162.5,24.990000,1474.409986,1324.469988,59.0,1.240000

In [4]:
df.dtypes

VendorNo                   int64
Brand                      int64
Description               object
FreightCost              float64
vendorname                object
purchaseprice            float64
TotalPurchaseQuantity      int64
TotalPurchaseDollar      float64
volume                    object
SellingPrice             float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalSalesQuantity       float64
TotalExciseTax           float64
dtype: object

In [5]:
df.isnull().sum()

VendorNo                   0
Brand                      0
Description                0
FreightCost                0
vendorname                 0
purchaseprice              0
TotalPurchaseQuantity      0
TotalPurchaseDollar        0
volume                     0
SellingPrice               0
TotalSalesDollars        178
TotalSalesPrice          178
TotalSalesQuantity       178
TotalExciseTax           178
dtype: int64

In [6]:
df['vendorname'].unique()

array(['IRA GOLDMAN AND WILLIAMS, LLP          ',
       'AAPER ALCOHOL & CHEMICAL CO', 'ADAMBA IMPORTS INTL INC    ',
       'ALTAMAR BRANDS LLC         ', 'AMERICAN SPIRITS EXCHANGE  ',
       'APPOLO VINEYARDS LLC       ', 'ATLANTIC IMPORTING COMPANY ',
       'BACARDI USA INC            ', 'BANFI PRODUCTS CORP        ',
       'STATE WINE & SPIRITS   ', 'SAZERAC NORTH AMERICA INC. ',
       'BRONCO WINE COMPANY        ', 'BROWN-FORMAN CORP          ',
       'BULLY BOY DISTILLERS       ', 'BLACK ROCK SPIRITS LLC     ',
       'CALEDONIA SPIRITS INC      ', 'CONSTELLATION BRANDS INC   ',
       'CAPSTONE INTERNATIONAL     ', 'CASTLE BRANDS CORP.        ',
       'VINEYARD BRANDS INC        ', 'VINEYARD BRANDS LLC        ',
       'DIAGEO CHATEAU ESTATE WINES', 'VRANKEN AMERICA            ',
       'Circa Wines                ', 'FABRIZIA SPIRITS LLC       ',
       'ALISA CARR BEVERAGES           ', 'SOUTHERN GLAZERS W&S OF NE ',
       'SOUTHERN WINE & SPIRITS NE ', 'DELICATO VINEYARDS INC     ',
       'BLACK PRINCE DISTILLERY INC', 'DJINN SPIRITS LLC          ',
       'DUGGANS DISTILLED PRODUCTS ', 'DISARONNO INTERNATIONAL LLC',
       'EDRINGTON AMERICAS         ', 'CENTEUR IMPORTS LLC        ',
       'SIDNEY FRANK IMPORTING CO  ', 'E & J GALLO WINERY         ',
       'GILMANTON WINERY & VINEYARD', 'WILLIAM GRANT & SONS INC   ',
       'HEAVEN HILL DISTILLERIES   ', 'HOOD RIVER DISTILLERS, Inc.',
       'HIGHLAND WINE MERCHANTS LLC', 'DIAGEO NORTH AMERICA INC   ',
       'CHARLES JACQUIN ET CIE INC ', 'MARTIGNETTI COMPANIES',
       'MARTIGNETTI COMPANIES ', 'AMERICAN VINTAGE BEVERAGE  ',
       'KLIN SPIRITS LLC           ', 'KOBRAND CORPORATION        ',
       'LAIRD & CO                 ', 'LAUREATE IMPORTS CO        ',
       'LATITUDE BEVERAGE COMPANY  ', 'LOYAL DOG WINERY           ',
       'MANGO BOTTLING INC         ', 'MARSALLE COMPANY           ',
       'MILTONS DISTRIBUTING CO    ', 'MCCORMICK DISTILLING CO    ',
       'MHW LTD                    ', 'MOONLIGHT MEADERY          ',
       'UNCORKED       ', 'NICHE W & S                ',
       'OLE SMOKY DISTILLERY LLC   ', 'PALM BAY INTERNATIONAL INC ',
       'PARK STREET IMPORTS LLC    ', 'PINE STATE TRADING CO      ',
       'PREMIER DISTRIBUTORS       ', 'REMY COINTREAU USA INC     ',
       'PREMIUM PORT WINES, INC.   ', 'PROXIMO SPIRITS INC.       ',
       'PSP WINES ', 'R.P.IMPORTS INC            ',
       'SAZERAC CO INC             ', 'MOET HENNESSY USA INC      ',
       'SEA HAGG DISTILLERY LLC    ', 'SHAW ROSS INT L IMP LTD    ',
       'LUXCO INC                  ', 'STAR INDUSTRIES INC.       ',
       'STOLI GROUP,(USA) LLC      ', 'STE MICHELLE WINE ESTATES  ',
       'SURVILLE ENTERPRISES CORP  ', 'TRINCHERO FAMILY ESTATES   ',
       'TAKARA SAKE USA INC        ', 'TRUETT HURST               ',
       'ULTRA BEVERAGE COMPANY LLP ', 'PHILLIPS PRODUCTS CO.      ',
       'TY KU LLC                  ', 'M S WALKER INC             ',
       'WEIN BAUER INC             ', 'WESTERN SPIRITS BEVERAGE CO',
       'FREDERICK WILDMAN & SONS   ', 'VINEDREA WINES LLC         ',
       'WINE GROUP INC             ', 'TREASURY WINE ESTATES      ',
       'MAJESTIC FINE WINES        ', 'Russian Standard Vodka     ',
       'PERFECTA WINES             ', 'CAMPARI AMERICA            ',
       'STELLAR IMPORTING CO LLC   ', 'JIM BEAM BRANDS COMPANY    ',
       'FLAG HILL WINERY & VINEYARD', 'JEWELL TOWNE VINEYARDS     ',
       'SEA BREEZE CELLARS LLC     ', 'PERNOD RICARD USA          ',
       'Dunn Wine Brokers          ', 'SMOKY QUARTZ DISTILLERY LLC',
       'TALL SHIP DISTILLERY LLC   ', 'VINEXTRA INC               ',
       'FORTUNE WINE BROKERS LLC   ', 'THE IMPORTED GRAPE LLC     ',
       'VINILANDIA USA             ', 'SILVER MOUNTAIN CIDERS     ',
       'POVERTY LANE ORCHARDS      ', 'LABELLE VYDS AND WINERY    ',
       'FANTASY FINE WINES CORP    ', 'THE PIERPONT GROUP LLC     ',
       'CANDIA VINEYARDS           ', 'CRUSH WINES                ',
       'FULCHINO VINEYARD INC      ', 'HAUNTING WHISPER VYDS      ',
       'INCREDIBREW INC            ', 'SWEET BABY VINEYARD        ',
       'WALPOLE MTN VIEW WINERY    ', 'ZORVINO VINEYARDS          ',
       'BLACK COVE BEVERAGES       ', 'Serralles Usa LLC          ',
       'STARK BREWING COMPANY      ', 'SWEETWATER FARM         ',
       'TAMWORTH DISTILLING        ', 'FLAVOR ESSENCE INC         '],
      dtype=object)

In [7]:
df['Description'].unique()

array(['Ch Lilian 09 Ladouys St Este', 'Flavor Essence Variety 5 Pak',
       'Ethyl Alcohol 200 Proof', ..., 'Art in the Age Chicory Root',
       'Chicory Root Vodka', 'White Mountain Vodka'],
      shape=(9651,), dtype=object)

In [8]:
df['volume'] = df['volume'].astype('float64')

In [9]:
df.fillna(0,inplace = True)

In [10]:
df['vendorname'] = df['vendorname'].str.strip()

In [11]:
df['GrossProfit'] = df['TotalSalesDollars']-df['TotalPurchaseDollar']

In [12]:
df['GrossProfit'].min()

-52002.778535842896

In [13]:
df['ProfitMargin'] = df['GrossProfit'] * 100 / df['TotalSalesDollars']

In [14]:
df['StockTurnover'] = df['TotalSalesQuantity'] / df['TotalPurchaseQuantity']

In [15]:
df['SalestoPurchaseRatio'] = df['TotalSalesDollars'] / df['TotalPurchaseDollar']

In [16]:
df

,VendorNo,Brand,Description,FreightCost,vendorname,purchaseprice,TotalPurchaseQuantity,TotalPurchaseDollar,volume,SellingPrice,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,2,90085,Ch Lilian 09 Ladouys St Este,27.080001,"IRA GOLDMAN AND WILLIAMS, LLP",23.860001,8,190.880005,750.0,36.990002,665.820019,295.920013,18.0,2.000000,474.940014,71.331591,2.250000,3.488160
1,2,90609,Flavor Essence Variety 5 Pak,27.080001,"IRA GOLDMAN AND WILLIAMS, LLP",17.000000,320,5440.000000,162.5,24.990000,599.759998,449.819996,24.0,0.520000,-4840.240002,-807.029481,0.075000,0.110250
2,54,990,Ethyl Alcohol 200 Proof,0.480000,AAPER ALCOHOL & CHEMICAL CO,105.070000,1,105.070000,3750.0,134.490005,0.000000,0.000000,0.0,0.000000,-105.070000,-inf,0.000000,0.000000
3,60,771,Bak's Krupnik Honey Liqueur,367.520002,ADAMBA IMPORTS INTL INC,11.440000,39,446.159996,750.0,14.990000,704.529989,494.669992,47.0,37.010001,258.369993,36.672675,1.205128,1.579097
4,60,3401,Vesica Vodka,367.520002,ADAMBA IMPORTS INTL INC,11.100000,6,66.599998,1750.0,14.990000,0.000000,0.000000,0.0,0.000000,-66.599998,-inf,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,173357,2804,Camp Robber Whiskey,202.500001,TAMWORTH DISTILLING,32.139999,210,6749.399887,750.0,44.990002,6298.600163,3194.290119,140.0,110.330001,-450.799725,-7.157141,0.666667,0.933209
10688,173357,3666,Art in the Age Chicory Root,202.500001,TAMWORTH DISTILLING,18.790001,520,9770.799988,375.0,24.990000,8996.399963,4873.049955,360.0,141.189998,-774.400024,-8.607888,0.692308,0.920743
10689,173357,3848,Chicory Root Vodka,202.500001,TAMWORTH DISTILLING,23.299999,28,652.400009,750.0,30.990000,185.939999,92.969999,6.0,4.710000,-466.460011,-250.865878,0.214286,0.285009
10690,173357,3909,White Mountain Vodka,202.500001,TAMWORTH DISTILLING,19.370001,1232,23863.840233,750.0,24.990000,24540.179880,14469.209867,982.0,773.870011,676.339647,2.756050,0.797078,1.028342
10691,201359,90609,Flavor Essence Variety 5 Pak,0.090000,FLAVOR ESSENCE INC,17.000000,1,17.000000,162.5,24.990000,1474.409986,1324.469988,59.0,1.240000,1457.409986,98.846996,59.000000,86.729999

In [17]:
print(np.isinf(df.select_dtypes(include=np.number)).sum())

VendorNo                   0
Brand                      0
FreightCost                0
purchaseprice              0
TotalPurchaseQuantity      0
TotalPurchaseDollar        0
volume                     0
SellingPrice               0
TotalSalesDollars          0
TotalSalesPrice            0
TotalSalesQuantity         0
TotalExciseTax             0
GrossProfit                0
ProfitMargin             178
StockTurnover              0
SalestoPurchaseRatio       0
dtype: int64

In [18]:
df = df.replace([np.inf,-np.inf],np.nan)

In [19]:
# Export clean data

df.to_csv('Clean_Vendor____Sales____Summary.csv',index= False)

In [20]:
# Import data into ssms

from sqlalchemy import create_engine

engine = create_engine(
    "mssql+pyodbc://RDsDevice\SQLEXPRESS01/Inventory"
    "?driver=ODBC+Driver+17+for+SQL+Server"
    "&trusted_connection=yes"
)

In [21]:
# Export dataframe to ssms

df.to_sql(
    name="Clean_Vendor____Sales____Summary",
    con=engine,
    if_exists="replace",
    index=False
)

C:\Users\rd000\anaconda3\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

20

In [22]:
df

,VendorNo,Brand,Description,FreightCost,vendorname,purchaseprice,TotalPurchaseQuantity,TotalPurchaseDollar,volume,SellingPrice,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,2,90085,Ch Lilian 09 Ladouys St Este,27.080001,"IRA GOLDMAN AND WILLIAMS, LLP",23.860001,8,190.880005,750.0,36.990002,665.820019,295.920013,18.0,2.000000,474.940014,71.331591,2.250000,3.488160
1,2,90609,Flavor Essence Variety 5 Pak,27.080001,"IRA GOLDMAN AND WILLIAMS, LLP",17.000000,320,5440.000000,162.5,24.990000,599.759998,449.819996,24.0,0.520000,-4840.240002,-807.029481,0.075000,0.110250
2,54,990,Ethyl Alcohol 200 Proof,0.480000,AAPER ALCOHOL & CHEMICAL CO,105.070000,1,105.070000,3750.0,134.490005,0.000000,0.000000,0.0,0.000000,-105.070000,NaN,0.000000,0.000000
3,60,771,Bak's Krupnik Honey Liqueur,367.520002,ADAMBA IMPORTS INTL INC,11.440000,39,446.159996,750.0,14.990000,704.529989,494.669992,47.0,37.010001,258.369993,36.672675,1.205128,1.579097
4,60,3401,Vesica Vodka,367.520002,ADAMBA IMPORTS INTL INC,11.100000,6,66.599998,1750.0,14.990000,0.000000,0.000000,0.0,0.000000,-66.599998,NaN,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,173357,2804,Camp Robber Whiskey,202.500001,TAMWORTH DISTILLING,32.139999,210,6749.399887,750.0,44.990002,6298.600163,3194.290119,140.0,110.330001,-450.799725,-7.157141,0.666667,0.933209
10688,173357,3666,Art in the Age Chicory Root,202.500001,TAMWORTH DISTILLING,18.790001,520,9770.799988,375.0,24.990000,8996.399963,4873.049955,360.0,141.189998,-774.400024,-8.607888,0.692308,0.920743
10689,173357,3848,Chicory Root Vodka,202.500001,TAMWORTH DISTILLING,23.299999,28,652.400009,750.0,30.990000,185.939999,92.969999,6.0,4.710000,-466.460011,-250.865878,0.214286,0.285009
10690,173357,3909,White Mountain Vodka,202.500001,TAMWORTH DISTILLING,19.370001,1232,23863.840233,750.0,24.990000,24540.179880,14469.209867,982.0,773.870011,676.339647,2.756050,0.797078,1.028342
10691,201359,90609,Flavor Essence Variety 5 Pak,0.090000,FLAVOR ESSENCE INC,17.000000,1,17.000000,162.5,24.990000,1474.409986,1324.469988,59.0,1.240000,1457.409986,98.846996,59.000000,86.729999